name: colan_services
description: "Various Services"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5
  camera: ^0.11.0+1
  cl_camera:
    path: ../cl_camera
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  device_resources:
    path: ../device_resources
  event_bus: ^2.0.0
  extended_image: ^8.2.1
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_factory:
    path: ../form_factory
  go_router: ^14.2.0
  heif_converter: ^1.0.0
  image: ^4.1.7
  image_picker: ^1.1.2
  intl: ^0.18.1
  local_store:
    path: ../local_store
  material_design_icons_flutter: ^7.0.7296
  mime: ^1.0.5
  path: ^1.9.0
  
  share_handler: ^0.0.21
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  store:
    path: ../store
  stream_channel: ^2.1.2
  tar: ^2.0.0
  uuid: ^4.4.0
  video_player: ^2.8.7
  video_thumbnail: ^0.5.3
  video_trimmer: ^3.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
 