name: colan_services
description: "Various Services"
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_icon: ^0.0.9
  audio_waveforms: 1.0.5 # Upgrade has issues!
  background_downloader: ^8.9.4
  camera: ^0.11.0+1

  cl_camera:
    path: ../cl_camera
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_media_tools:
    path: ../cl_media_tools
  cl_media_viewers_flutter:
    path: ../cl_media_viewers_flutter
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0

  connectivity_plus: ^6.0.5
  content_store:
    path: ../content_store
  dio: ^5.7.0
  event_bus: ^2.0.0
  exif: ^3.3.0
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_speed_dial: ^7.0.0
  font_awesome_flutter: ^10.8.0
  form_factory:
    path: ../form_factory

  heif_converter: ^1.0.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image: ^4.1.7
  image_picker: ^1.1.2

  local_store:
    path: ../local_store
  logger: ^2.4.0

  lucide_icons_flutter: ^1.3.0
  material_design_icons_flutter: ^7.0.7296
  media_editors:
    path: ../media_editors

  meta: ^1.12.0
  mime: ^2.0.0
  multicast_dns: ^0.3.2+7
  mutex: ^3.1.0
  nsd: ^4.0.3
  path: ^1.9.0

  path_provider: ^2.1.4
  percent_indicator: ^4.2.5
  photo_manager: ^3.2.3
  pie_chart: ^5.4.0
  progress_indicators: ^1.0.0
  pull_down_button: ^0.10.2

  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui
  share_handler: ^0.0.21
  share_plus: ^10.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  store:
    path: ../store
  stream_channel: ^2.1.2
  tar: ^2.0.0
  uuid: ^4.4.0
  video_player: ^2.8.7
  video_thumbnail: ^0.5.3

  watcher: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0

  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
