name: colan_services
description: "Various Services"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  camera: ^0.10.5+9
  cl_camera:
    path: ../cl_camera
  colan_widgets:
    path: ../colan_widgets
  event_bus: ^2.0.0
  extended_image: ^8.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  heif_converter: ^1.0.0
  image: ^4.1.7
  material_design_icons_flutter: ^7.0.7296
  mime: ^1.0.5
  path: ^1.9.0
  store:
    path: ../store
  stream_channel: ^2.1.2
  uuid: ^4.4.0
  video_player: ^2.8.6
  video_thumbnail: ^0.5.3
  video_trimmer: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
