name: colan_services
description: "Various Services"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audio_waveforms: ^1.0.5
  camera: ^0.11.0+1
  cl_camera:
    path: ../cl_camera
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  device_resources:
    path: ../device_resources
  event_bus: ^2.0.0
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  heif_converter: ^1.0.0
  image: ^4.1.7
  intl: ^0.18.1
  material_design_icons_flutter: ^7.0.7296
  mime: ^1.0.5
  path: ^1.9.0
  photo_manager: ^3.2.0
  shared_preferences: ^2.2.3
  stream_channel: ^2.1.2
  uuid: ^4.4.0
  video_player: ^2.8.7
  video_thumbnail: ^0.5.3
  video_trimmer: ^3.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
