name: app_loader
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.cloudonlanapps.com

publish_to: none
environment:
  sdk: ">=3.1.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.17.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.1
  
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.7
  logger: ^2.0.2+1
  mime: ^1.0.5
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  progress_indicators: ^1.0.0
  share_handler: ^0.0.19
  
  very_good_analysis: ^5.1.0
  video_thumbnail: ^0.5.3
    
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

