name: app_loader
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.cloudonlanapps.com

publish_to: none
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  colan_services:
    path: ../colan_services
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  content_store:
    path: ../content_store
  
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_speed_dial: ^7.0.0
  go_router: ^14.2.0
  image_picker: ^1.1.2
  share_handler: ^0.0.21
  
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  
flutter:

