name: colan_widgets
description: "Widgets for Colan Projects"
version: 0.0.1

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  http: ^1.2.0
  http_parser: ^4.0.2
  image: ^4.1.4
  intl: ^0.19.0
  logger: ^2.0.2+1
  mime: ^1.0.5
  path: ^1.8.3
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  progress_indicators: ^1.0.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_handler: ^0.0.20
  stream_channel: ^2.1.2
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3 
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
flutter:
