name: colan_widgets
description: "Widgets for Colan Projects"
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5 
  collection: ^1.19.0
  crypto: ^3.0.3
  event_bus: ^2.0.0
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  
  http: ^1.2.0
  http_parser: ^4.0.2
  logger: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2785.1
  path: ^1.9.0
  percent_indicator: ^4.2.3
  
  progress_indicators: ^1.0.0
  shimmer: ^3.0.0
  
  #scroll_to_index: ^3.0.1
  # scrollable_positioned_list: ^0.3.8
  # watcher: ^1.1.0
  
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  
flutter:
  uses-material-design: true
