name: colan_widgets
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  http: ^1.2.0
  http_parser: ^4.0.2
  image: ^4.1.4
  intl: ^0.19.0
  iso: ^1.0.0
  logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.2
  progress_indicators: ^1.0.0
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  share_handler: ^0.0.20
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0
  video_player: ^2.8.2
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
