name: colan_widgets
description: "Widgets for Colan Projects"
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  audio_waveforms: ^1.0.5 
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  crypto: ^3.0.3
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  http: ^1.2.0
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  intl: ^0.18.1
  logger: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  multicast_dns: ^0.3.2+7
  path: ^1.9.0
  percent_indicator: ^4.2.3
  
  progress_indicators: ^1.0.0
  share_handler: ^0.0.21
  shared_preferences: ^2.3.1
  store:
    path: ../store
  
  #scroll_to_index: ^3.0.1
  # scrollable_positioned_list: ^0.3.8
  # watcher: ^1.1.0
  
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  
flutter:
