name: colan_widgets
description: "Widgets for Colan Projects"
version: 0.0.1

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  audio_waveforms: ^1.0.5
  crypto: ^3.0.3
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  http: ^1.2.0
  http_parser: ^4.0.2
  intl: ^0.18.0
  logger: ^2.1.0
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  percent_indicator: ^4.2.3
  photo_manager: ^3.1.1
  progress_indicators: ^1.0.0
  
  scroll_to_index: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  
  
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  
flutter:
