name: store
description: "An futter project that allow you to store images & video and more formating. Allows you to arrange the collection!"
version: 0.2.1
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  crypto: ^3.0.3
  event_bus: ^2.0.0
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  heif_converter: ^1.0.0
  image: ^4.1.7
  intl: ^0.18.0
  mime: ^1.0.5
  path: ^1.8.3
  path_provider: ^2.1.1
  
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.6.0
  stream_channel: ^2.1.2
  uuid: ^4.3.3
  very_good_analysis: ^5.1.0
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
