name: store
description: "An futter project that allow you to store images & video and more formating. Allows you to arrange the collection!"
version: 0.2.1
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path: ^1.8.3
  path_provider: ^2.1.1
  photo_manager: ^3.1.1
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.6.0
  
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0


flutter:
