name: store
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  cl_basic_types:
    path: ../cl_basic_types
  cl_entity_viewers:
    path: ../cl_entity_viewers
  collection: ^1.19.0
  crypto: ^3.0.4
  heif_converter: ^1.0.1
  http: ^1.2.2
  image: ^4.5.4
  intl: ^0.20.2
  logger: ^2.4.0
  meta: ^1.12.0 # this version 1.12.0 is required for flutter_test
  path: ^1.9.0
  shared_preferences: ^2.3.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0
