name: store
description: "An futter project that allow you to store images & video and more formating. Allows you to arrange the collection!"
version: 0.2.1
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  device_resources:
    path: ../device_resources
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  form_factory:
    path: ../form_factory
  go_router: ^14.2.0
  image_picker: ^1.1.2
  
  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  
  share_handler: ^0.0.21
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.7.0
  tar: ^2.0.0
  
  
  
  
  
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
