name: store_model
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  exif: ^3.3.0
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  intl: ^0.19.0
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  
  very_good_analysis: ^6.0.0

flutter:
