name: content_store
description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  background_downloader: ^8.5.6
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_speed_dial: ^7.0.0
  http: ^1.2.2
  meta: ^1.12.0
  pie_chart: ^5.4.0
  store:
    path: ../store


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
