name: content_store
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  #background_downloader: ^8.9.4
  cl_basic_types:
    path: ../cl_basic_types
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_media_tools:
    path: ../cl_media_tools
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0
  connectivity_plus: ^6.0.5
  exif: ^3.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_speed_dial: ^7.0.0
  heif_converter: ^1.0.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image: ^4.2.0
  intl: ^0.20.2

  local_store:
    path: ../local_store
  meta: ^1.12.0
  mime: ^2.0.0
  nsd: ^4.0.3
  online_store:
    path: ../online_store
  path: ^1.9.0
  path_provider: ^2.1.4
  photo_manager: ^3.5.0
  pie_chart: ^5.4.0
  shadcn_ui: ^0.27.0
  share_plus: ^11.0.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  store:
    path: ../store
  uuid: ^4.5.1
  watcher: ^1.1.0
  yet_another_date_picker:
    path: ../yet_another_date_picker

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^8.0.0
