name: cl_entity_viewers
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.cloudonlanapps.com
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cl_media_tools:
    path: ../cl_media_tools
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  intl: ^0.19.0
  shadcn_ui: ^0.24.0
  yet_another_date_picker:
    path: ../yet_another_date_picker

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
