name: cl_entity_viewers
description: "A new Flutter package project."
version: 0.0.1
homepage: https://www.cloudonlanapps.com
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  intl: ^0.19.0
  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
