name: cl_entity_viewers
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  intl: ^0.19.0
  meta: ^1.15.0
  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
