name: store_tasks
description: "store_tasks package."
version: 0.0.1

publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cl_entity_viewers:
    path: ../cl_entity_viewers
  cl_media_tools:
    path: ../cl_media_tools
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.1
  content_store:
    path: ../content_store
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  form_factory:
    path: ../form_factory
  shadcn_ui: ^0.27.0
  shimmer: ^3.0.0
  store:
    path: ../store

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^8.0.0

flutter:
  uses-material-design: true
  generate: false
