name: server_test
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  cl_entity_viewers:
    path: ../cl_entity_viewers
  flutter:
    sdk: flutter
  server:
    path: ../server
  store_revised:
    path: ../store_revised
  cupertino_icons: ^1.0.8
  signals: ^6.0.2
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  collection: ^1.19.0
  shadcn_ui:
    path: /Users/anandasarangaram/Work/flutter-shadcn-ui
  meta: ^1.15.0
  shared_preferences: ^2.5.2
  connectivity_plus: ^6.1.3
  nsd: ^4.0.3
  material_design_icons_flutter: ^7.0.7296
  multi_split_view: ^3.6.0
  flutter_solidart: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
