name: cl_basic_types
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  meta: ^1.16.0
  collection: ^1.19.1
  crypto: ^3.0.6
  path: ^1.9.1
  intl: ^0.20.2
  exif: ^3.3.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
