name: device_resources
description: "Device Resources"
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  
  exif: ^3.3.0
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_manager: ^3.2.0
  share_plus: ^9.0.0
  watcher: ^1.1.0


dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
