name: media_editors
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  extended_image: ^8.2.1
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  image: ^4.2.0
  shared_preferences: ^2.3.2
  video_trimmer: ^3.0.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
