name: media_editors
description: "A new Flutter package project."
version: 0.0.1

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.19.0
  extended_image: ^9.1.0
  ffmpeg_kit_flutter: ^6.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  image: ^4.2.0
  shared_preferences: ^2.3.2
  video_trimmer: 
    path: /Users/anandasarangaram/Work/video_trimmer 

dev_dependencies:
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
