name: server
description: A starting point for Dart libraries or applications.
version: 1.0.0

publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  collection: ^1.19.0
  http: ^1.3.0
  meta: ^1.15.0
  riverpod: ^2.5.1
  store:
    path: ../store

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
