name: colan_cmdline
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  collection: ^1.18.0
  http: ^1.2.2
  json_diff: ^0.2.1
  logger: ^2.4.0
  meta: ^1.12.0
  # path: ^1.8.0
  path: ^1.9.0
  sqlite_async: ^0.7.0
  store:
    path: ../store

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
