name: local_store
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  
  collection: ^1.18.0
  meta: ^1.12.0
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.8.0
  store:
    path: ../store
  test_api: ^0.7.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0

