name: local_store
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  colan_widgets:
    path: ../colan_widgets
  collection: ^1.18.0
  flutter:
    sdk: flutter
  
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.6.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter: