name: local_store
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  cl_media_tools:
    path: ../cl_media_tools
  collection: ^1.19.0
  http: ^1.2.2
  meta: ^1.12.0
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.4
  sqlite3_flutter_libs: ^0.5.20
  sqlite_async: ^0.11.1
  store:
    path: ../store
  test_api: ^0.7.0

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0
  very_good_analysis: ^7.0.0
