name: media_viewers
description: "A new Flutter package project."
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  colan_widgets:
    path: ../colan_widgets
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  video_player: ^2.9.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
